name: Pylint

on: [push]

jobs:
  lint_code:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Show current directory content
      run: |
        ls -la
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
